comp115911_c0_seq1	43	N	3	^]T^]T^]T	hhf
comp115911_c0_seq1	44	N	3	CCC	hhf
comp115911_c0_seq1	45	N	3	AAA	hff
comp115911_c0_seq1	46	N	3	AAA	hfd
comp115911_c0_seq1	47	N	5	CCC^>C^]T	hhfh!
comp115911_c0_seq1	48	N	7	TTTTT^]T^]T	hhfh!!!
comp115911_c0_seq1	49	N	7	GGGGGGG	ghfh!!!
comp115911_c0_seq1	50	N	9	AAAAAAA^]T^]T	hhfh!!!!!
comp115911_c0_seq1	51	N	9	CCCCCCCCC	hhfh!!!!!
comp115911_c0_seq1	52	N	10	GGGGGGGGG^>G	hhfh!!!!!!
comp115911_c0_seq1	53	N	10	GGGGGGGGGG	ghdh!!!!!!
comp115911_c0_seq1	54	N	10	AAAAAAAAAA	h_fh!!!!!!
comp115911_c0_seq1	55	N	10	TTTTTTTTTT	hhff!!!!!!
comp115911_c0_seq1	56	N	10	TTTTTTTTTT	ghfh!!!!!!
comp115911_c0_seq1	57	N	11	AAAAAAAAAA^]a	hffg!!!!!!!
comp115911_c0_seq1	58	N	11	AAAAAAAAAAa	hgfh!!!!!!!
comp115911_c0_seq1	59	N	11	CCCCCCCCCCc	hhfh!!!!!!!
comp115911_c0_seq1	60	N	12	GGGGGGGGGGg^>G	hhfg!!!!!!!!
comp115911_c0_seq1	61	N	12	TTTTTTTTTTtT	gafh!!!!!!!!
comp115911_c0_seq1	62	N	12	GGGGGGGGGGgG	hcfh!!!!!!!!
comp115911_c0_seq1	63	N	12	AAAAAAAAAAaA	fffg!!!!!!!!
comp115911_c0_seq1	64	N	12	TTTTTTTTTTtT	fffg!!!!!!!!
comp115911_c0_seq1	65	N	12	CCCCCCCCCCcC	hffh!!!!!!!!
comp115911_c0_seq1	66	N	13	CCCCCCCCCCcC^]T	hffh!!!!!!!!!
comp115911_c0_seq1	67	N	14	CCCCCCCCCCcCC^]C	hhfh!!!!!!!!!!
comp115911_c0_seq1	68	N	14	GGGGGGGGGGgGGG	hhff!!!!!!!!!!
comp115911_c0_seq1	69	N	15	CCCCCCCCCCcCCC^]c	hhfh!!!!!!!!!!!
comp115911_c0_seq1	70	N	15	GGGGGGGGGGgGGGg	hheh!!!!!!!!!!!
comp115911_c0_seq1	71	N	15	AAAAAAAAAAaAAAa	hhdh!!!!!!!!!!!
comp115911_c0_seq1	72	N	16	AAAAAAAAAAaAAAa^>A	haff!!!!!!!!!!!!
comp115911_c0_seq1	73	N	16	TTTTTTTTTTtTTTtT	hhfh!!!!!!!!!!!!
comp115911_c0_seq1	74	N	17	TTTTTTTTT.tTTTtT^>T	hhff!!!!!!!!!!!!!
comp115911_c0_seq1	75	N	17	AAAAAAAAA.aAAAaAA	ccfh!!!!!!!!!!!!!
comp115911_c0_seq1	76	N	18	AAAAAAAAA.aAAAaAA^]A	hhfh!!!!!!!!!!!!!!
comp115911_c0_seq1	77	N	18	TTTTTTTTT.tTTTtTTT	hhfh!!!!!!!!!!!!!!
comp115911_c0_seq1	78	N	18	AAAAAAAAA.aAAAaATA	hhff!!!!!!!!!!!!!!
comp115911_c0_seq1	79	N	18	GGGGGGGGG.gGGGgGGG	h]fg!!!!!!!!!!!!!!
comp115911_c0_seq1	80	N	21	TTTTTTTTT.tTTTtTGT^>T^]T^]T	hede!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	81	N	22	GGGGGGGGGGgGGGgGGGGGG^]G	fhff!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	82	N	22	GGGGGGGGGGgGGGgGGGGGGG	hfch!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	83	N	22	TTTTTTTTTTtTTTtTGTTTTT	eaeg!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	84	N	22	GGGGGGGGGGgGGGgGGGGGGG	hhfh!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	85	N	22	TTTTTTTTTTtTTTtTTTGTTT	gech!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	86	N	23	AAAAAAAAAAaAAAaAAAAAAA^]T	ghee!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	87	N	23	TTTTTTTTTTtTTTtTATTTTTT	ehfh!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	88	N	23	AAAAAAAAAAaAAAaAAAAAAAA	ggff!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	89	N	23	AAAAAAAAAAaAAAaAAAAAAAA	gefh!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	90	N	23	AAAAAAAAAAaAAAaAAAAAAAA	hech!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	91	N	23	AAAAAAAAAAaAAAaAAAAAAAA	h`fh!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	92	N	23	AAAAAAAAAAaAAAaAAAAAAAA	hhfc!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	93	N	23	AAAAAAAAAAaAAAaAA$AAAAAA	eeeh!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	94	N	22	CCCCCCCCCCcCCCcCCCCCCC	hgfh!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	95	N	22	GGGGGGGGGGgGGGgGGGGGGG	defh!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	96	N	22	A$A$A$AAAAAAAaAAAaAAAAAAA	fcfh!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	97	N	19	TTTTTTTtTTTtTTTTTTT	h!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	98	N	19	TTTTTTTtTTTtTTTTTTT	h!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	99	N	19	T$TTTTTTtTTTtTTTTTTT	h!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	100	N	18	T$TT$TTTtTTTtTTTTTTT	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	101	N	16	A$AAAaAAAaAAAAAAA	!!!!!!!!!!!!!!!!
comp115911_c0_seq1	102	N	15	AAAaAAAaAAAAAAA	!!!!!!!!!!!!!!!
comp115911_c0_seq1	103	N	15	A$A$AaAAAaAAAAAAA	!!!!!!!!!!!!!!!
comp115911_c0_seq1	104	N	13	C$cCCCcCCCCCCC	!!!!!!!!!!!!!
comp115911_c0_seq1	105	N	12	aAAAaAAAAAAA	!!!!!!!!!!!!
comp115911_c0_seq1	106	N	12	cC$CCcCCCCCCC	!!!!!!!!!!!!
comp115911_c0_seq1	107	N	11	gGGgGGGGGGG	!!!!!!!!!!!
comp115911_c0_seq1	108	N	11	aAAaAAAAAAA	!!!!!!!!!!!
comp115911_c0_seq1	109	N	11	t$TTtTTTTTTT	!!!!!!!!!!!
comp115911_c0_seq1	110	N	10	GGgGGGGGGG	!!!!!!!!!!
comp115911_c0_seq1	111	N	10	TTtTTTTTTT	!!!!!!!!!!
comp115911_c0_seq1	112	N	10	AAaAAAAAAA	!!!!!!!!!!
comp115911_c0_seq1	113	N	11	TTtTTTTTTT^]T	!!!!!!!!!!!
comp115911_c0_seq1	114	N	11	GGgGGGGGGGG	!!!!!!!!!!!
comp115911_c0_seq1	115	N	11	TTtTTTTTTTT	!!!!!!!!!!!
comp115911_c0_seq1	116	N	12	AAaAAA$AAAAA^]A	!!!!!!!!!!!!
comp115911_c0_seq1	117	N	12	GGgG$GGGGGGG^>g	!!!!!!!!!!!!
comp115911_c0_seq1	118	N	11	AAaAAAAAAAa	!!!!!!!!!!!
comp115911_c0_seq1	119	N	11	A$A$aAAAAAAAa	!!!!!!!!!!!
comp115911_c0_seq1	120	N	9	aAAAAAAAa	!!!!!!!!!
comp115911_c0_seq1	121	N	9	t$TTTTTTTt	!!!!!!!!!
comp115911_c0_seq1	122	N	9	AAAAAAAa^]A	!!!!!!!!!
comp115911_c0_seq1	123	N	9	AAAAAAAaA	!!!!!!!!!
comp115911_c0_seq1	124	N	9	TTTTTTTtT	!!!!!!!!!
comp115911_c0_seq1	125	N	9	AAAAAAAaA	!!!!!!!!!
comp115911_c0_seq1	126	N	10	TTTTTTTtT^]T	!!!!!!!!!!
comp115911_c0_seq1	127	N	10	AAAAAAAaAA	!!!!!!!!!!
comp115911_c0_seq1	128	N	10	T$TTTTTTtTT	!!!!!!!!!!
comp115911_c0_seq1	129	N	9	TTTTTTtTT	!!!!!!!!!
comp115911_c0_seq1	130	N	10	CCCCCCcCC^]c	!!!!!!!!!!
comp115911_c0_seq1	131	N	10	TTTTTTtTTt	!!!!!!!!!!
comp115911_c0_seq1	132	N	10	TTTTTTtTTt	!!!!!!!!!!
comp115911_c0_seq1	133	N	10	T$T$T$TTTtTTt	!!!!!!!!!!
comp115911_c0_seq1	134	N	7	AAAaAAa	!!!!!!!
comp115911_c0_seq1	135	N	7	TTTtTTt	!!!!!!!
comp115911_c0_seq1	136	N	7	AAAaAAa	!!!!!!!
comp115911_c0_seq1	137	N	7	CCCcCCc	!!!!!!!
comp115911_c0_seq1	138	N	7	AAAaAAa	!!!!!!!
comp115911_c0_seq1	139	N	7	T$TTtTTt	!!!!!!!
comp115911_c0_seq1	140	N	6	AAaAAa	!!!!!!
comp115911_c0_seq1	141	N	6	AAaAAa	!!!!!!
comp115911_c0_seq1	142	N	6	TTtTTt	!!!!!!
comp115911_c0_seq1	143	N	6	AAaAAa	!!!!!!
comp115911_c0_seq1	144	N	6	TTtTTt	!!!!!!
comp115911_c0_seq1	145	N	6	AAaAAa	!!!!!!
comp115911_c0_seq1	146	N	7	TTtTTt^]t	!!!!!!!
comp115911_c0_seq1	147	N	7	AAaAAaa	!!!!!!!
comp115911_c0_seq1	148	N	7	TTtTTtt	!!!!!!!
comp115911_c0_seq1	149	N	7	AAaAAaa	!!!!!!!
comp115911_c0_seq1	150	N	7	AAaAAaa	!!!!!!!
comp115911_c0_seq1	151	N	7	TTtTTtt	!!!!!!!
comp115911_c0_seq1	152	N	7	AAaAAaa	!!!!!!!
comp115911_c0_seq1	153	N	7	TTtTTtt	!!!!!!!
comp115911_c0_seq1	154	N	7	AAaAAaa	!!!!!!!
comp115911_c0_seq1	155	N	7	TTtTTtt	!!!!!!!
comp115911_c0_seq1	156	N	7	TTtTTtt	!!!!!!!
comp115911_c0_seq1	157	N	7	AAaAAaa	!!!!!!!
comp115911_c0_seq1	158	N	7	TTtTTtt	!!!!!!!
comp115911_c0_seq1	159	N	7	GGgGGgg	!!!!!!!
comp115911_c0_seq1	160	N	7	TTtTTtt	!!!!!!!
comp115911_c0_seq1	161	N	10	GGgGGgg^]G^]G^]g	!!!!!!!!!!
comp115911_c0_seq1	162	N	10	TTtTTttTTt	!!!!!!!!!!
comp115911_c0_seq1	163	N	11	AAaAAaaAAa^>A	!!!!!!!!!!!
comp115911_c0_seq1	164	N	11	TTtTTttTTtT	!!!!!!!!!!!
comp115911_c0_seq1	165	N	11	TTtTTttTTtT	!!!!!!!!!!!
comp115911_c0_seq1	166	N	11	A$AaAAaaAAaA	!!!!!!!!!!!
comp115911_c0_seq1	167	N	10	TtTTttTTtT	!!!!!!!!!!
comp115911_c0_seq1	168	N	10	C$cCCccCCcC	!!!!!!!!!!
comp115911_c0_seq1	169	N	11	a$AAaaAAaA^>A^>a	!!!!!!!!!!!
comp115911_c0_seq1	170	N	10	TTttTTtTTt	!!!!!!!!!!
comp115911_c0_seq1	171	N	10	CCccCCcCCc	!!!!!!!!!!
comp115911_c0_seq1	172	N	10	GGggGGgGGg	!!!!!!!!!!
comp115911_c0_seq1	173	N	10	CCccCCcCCc	!!!!!!!!!!
comp115911_c0_seq1	174	N	10	A$AaaAAaAAa	!!!!!!!!!!
comp115911_c0_seq1	175	N	9	TttTTtTTt	!!!!!!!!!
comp115911_c0_seq1	176	N	9	TttTTtTTt	!!!!!!!!!
comp115911_c0_seq1	177	N	9	TttTTtTTt	!!!!!!!!!
comp115911_c0_seq1	178	N	10	TttTTtTTt^>t	!!!!!!!!!!
comp115911_c0_seq1	179	N	10	C$ccCCcCCcc	!!!!!!!!!!
comp115911_c0_seq1	180	N	9	ggGGgGGgg	!!!!!!!!!
comp115911_c0_seq1	181	N	9	aaAAaAAaa	!!!!!!!!!
comp115911_c0_seq1	182	N	9	c$cCCcCCcc	!!!!!!!!!
comp115911_c0_seq1	183	N	8	aAAaAAaa	!!!!!!!!
comp115911_c0_seq1	184	N	8	aAAaAAaa	!!!!!!!!
comp115911_c0_seq1	185	N	8	gGGgGGgg	!!!!!!!!
comp115911_c0_seq1	186	N	9	tTTtTTtt^>t	!!!!!!!!!
comp115911_c0_seq1	187	N	10	tTTtTTttt^]T	!!!!!!!!!!
comp115911_c0_seq1	188	N	11	tTTtTTtttT^]t	!!!!!!!!!!!
comp115911_c0_seq1	189	N	12	tTTtTTtttTt^]t	!!!!!!!!!!!!
comp115911_c0_seq1	190	N	12	tTTtTTtttTtt	!!!!!!!!!!!!
comp115911_c0_seq1	191	N	12	tTTtTTtttTtt	!!!!!!!!!!!!
comp115911_c0_seq1	192	N	13	gGGgGGgggGgg^]g	!!!!!!!!!!!!!
comp115911_c0_seq1	193	N	14	tTTtTTtttTttt^>t	!!!!!!!!!!!!!!
comp115911_c0_seq1	194	N	16	tTTtTTtttTtttt^>t^]t	!!!!!!!!!!!!!!!!
comp115911_c0_seq1	195	N	16	aAAaAAaaaAaaaaaa	!!!!!!!!!!!!!!!!
comp115911_c0_seq1	196	N	16	tTTtTTtttTtttttt	!!!!!!!!!!!!!!!!
comp115911_c0_seq1	197	N	16	gGGgGGgggGgggggg	!!!!!!!!!!!!!!!!
comp115911_c0_seq1	198	N	16	c$CCcCCcccCcccccc	!!!!!!!!!!!!!!!!
comp115911_c0_seq1	199	N	17	TTtTTtttTtttttt^]t^]t	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	200	N	17	CCcCCcccCcccccccc	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	201	N	17	CTtTTtttTtttttttt	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	202	N	17	TTtTTtttTtttttttt	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	203	N	18	TTtTTtttTtttttttt^]t	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	204	N	19	CCcCCcccCccccccccc^]c	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	205	N	19	AAaAAaaaAaaaaaaaaaa	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	206	N	19	TTtTTtttTtttttttttt	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	207	N	19	AAaAAaaaAaaaaaaaaaa	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	208	N	19	TTtTTtttTtttttttttt	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	209	N	19	TTtTTtttTtttttttttt	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	210	N	19	AAaAAaaaAaaaaaaaaaa	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	211	N	19	TTtTTtttTtttttttttt	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	212	N	19	GGgGGgggGgggggggggg	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	213	N	21	A$A$aAAaaaAaaaaaaaaaa^]T^]a	!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	214	N	19	a$TTtttTttttttttttTt	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	215	N	19	G$Gggg$GggggggggggGg^>G	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	216	N	17	TttTttttttttttTtT	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	217	N	17	TttTttttttttttTtT	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	218	N	17	TttTttttttttttTtT	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	219	N	18	AaaAaaaaaaaaaaAaA^]T	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	220	N	18	TttTttttttttttTtTT	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	221	N	19	G$g$gGggggggggggGgGG^]g	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	222	N	17	cCccccccccccCcCCc	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	223	N	17	tTttttttttttTtTTt	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	224	N	17	aAaaaaaaaaaaAaAAa	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	225	N	17	tTttttttttttTtTTt	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	226	N	17	tTttttttttttTtTTt	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	227	N	18	aAaaaaaaaaaaAaAAa^]a	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	228	N	18	aAaaaaaaaaaaAaAAaa	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	229	N	18	aAaaaaaaaaaaAaAAaa	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	230	N	18	tTttttttttttTtTTtt	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	231	N	18	a$AaaaaaaaaaaAaAAaa	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	232	N	18	TttttttttttTtTTtt^]T	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	233	N	18	AaaaaaaaaaaAaAAaaA	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	234	N	19	GggggggggggGgGGggG^]T	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	235	N	19	TttttttttttTtTTttTT	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	236	N	19	TttttttttttTtTTttTT	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	237	N	19	CccccccccccCcCCccCC	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	238	N	20	AaaaaaaaaaaAaAAaaAA^]A	!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	239	N	20	A$aaaaaaaaaaAaAAaaAAA	!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	240	N	19	a$aaaaaaaaaAaAAaaAAA	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	241	N	19	t$ttttttttTtTTttTTG^]T	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	242	N	18	aaaaaaaaAaAAaaAAAA	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	243	N	19	ggggggggGgGGggGGGG^]G	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	244	N	19	c$cccccccCcCCccCCCCC	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	245	N	18	c$ccccccCcCCccCCCCC	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	246	N	17	g$gggggGgGGggGGGGG	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	247	N	16	a$aaaaAaAAaaAAAAA	!!!!!!!!!!!!!!!!
comp115911_c0_seq1	248	N	15	ccccCcCCccCCCCC	!!!!!!!!!!!!!!!
comp115911_c0_seq1	249	N	15	ggggGgGGggGGGGG	!!!!!!!!!!!!!!!
comp115911_c0_seq1	250	N	15	aaaaAaAAaaAAAAA	!!!!!!!!!!!!!!!
comp115911_c0_seq1	251	N	15	c$c$ccCcCCccCCCCC	!!!!!!!!!!!!!!!
comp115911_c0_seq1	252	N	13	ggGgG$GggGGGGG	!!!!!!!!!!!!!
comp115911_c0_seq1	253	N	13	aaAaAaaAAAAA^]a	!!!!!!!!!!!!!
comp115911_c0_seq1	254	N	16	aaAaAaaAAAAAa^]a^]a^]a	!!!!!!!!!!!!!!!!
comp115911_c0_seq1	255	N	19	g$gGgGggGGGGGgggg^]G^>g^>g	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	256	N	18	a$AaAaaAAAAAaaaaAaa	!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	257	N	17	CcCccCCCCCccccCcc	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	258	N	19	GgGggGGGGGggggGgg^]g^]g	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	259	N	19	AaAaaAAAAAaaaaAaaaa	!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	260	N	20	AaAaaAAAAAaaaaAaaaa^]a	!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	261	N	20	TtTttTTTTTttttTttttt	!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	262	N	20	TtTttTTTTTttttTttttt	!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	263	N	20	TtTttTTTTTttttTttttt	!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	264	N	20	TtTttTTTTTttttTttttt	!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	265	N	22	CcCccCCCCCccccCccccc^]c^]c	!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	266	N	22	T$a$TttTTTTTttttTttttttt	!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	267	N	20	GggGGGGGggggGggggggg	!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	268	N	21	GggGGGGGggggGggggggg^]g	!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	269	N	21	AaaAAAAAaaaaAaaaaaaaa	!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	270	N	21	GggGGGGGggggGgggggggg	!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	271	N	21	CccCCCCCccccCcccccccc	!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	272	N	21	A$aaAAAAAaaaaAaaaaaaaa	!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	273	N	25	ggGGGGGggggGgggggggg^]G^]G^>G^]G^]G	!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	274	N	27	a$aAAAAAaaaaAaaaaaaaaAAAAA^>A^]A	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	275	N	27	cCCCCCccccCccccccccCCCCCCC^]c	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	276	N	27	gGGGTGggggGggggggggGGGGGGGg	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	277	N	27	aACAAAaaaaAaaaaaaaaAAAAAAAa	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	278	N	27	aAAAAAaaaaAaaaaaaaaAAAAAAAa	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	279	N	27	c$CCCGCccccCccccccccCCCCCCCc	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	280	N	27	TTTTTttttTttttttttTTTTTTTt^>T	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	281	N	27	AAAAAaaaaAaaaaaaaaAAAAAAAaA	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	282	N	27	TTTTTttttTttttttttTTTTTTTtT	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	283	N	27	AAAAAaaaaAaaaaaaaaAAAAAAAaA	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	284	N	27	GGGGGggggGggggggggGGGGGGGgG	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	285	N	27	A$AAAAaaaaAaaaaaaaaAAAAAAAaA	!!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	286	N	26	TTTTttttTttttttttTTTTTTTtT	!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	287	N	26	C$CCCccccCccccccccCCCCCCCcC	!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	288	N	26	TTTttttTttttttttTTTTTTTtT^]T	!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	289	N	26	GGGggggGggggggggGGGGGGGgGG	!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	290	N	26	T$TTttttTttttttttTTTTTTTtTT	!!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	291	N	25	GGggggGggggggggGGGGGGGgGG	!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	292	N	25	AAaaaaAaaaaaaaaAAAAAAAaAA	!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	293	N	25	GGggggGggggggggGGGGGGGgGG	!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	294	N	25	A$AaaaaAaaaaaaaaAAAAAAAaAA	!!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	295	N	24	A$aaaaAaaaaaaaaAAAAAAAaAA	!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	296	N	23	aaaaAaaaaaaaaAAAAAAAaAA	!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	297	N	24	ttttTttttttttTTTTTTTtTT^]T	!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	298	N	24	ggggGggggggggGGGGGGGgGGG	!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	299	N	24	aaaaAaaaaaaaaAAAAAAAaAAA	!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	300	N	24	aaaaAaaaaaaaaAAAAAAAaAAA	!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	301	N	24	aaaaAaaaaaaaaAAAAAAAaAAA	!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	302	N	24	ccccCccccccccCCCCCCCcCCC	!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	303	N	24	ttttTttttttttTTTTTTTtTTT	!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	304	N	24	ggggGggggggggGGGGGGGgGGG	!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	305	N	24	t$tttTttttttttTTTTTTTtTTT	!!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	306	N	23	gaaAa$a$aaaaaaAAAAAAAaAAA	!!!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	307	N	21	a$a$a$C$ccccccCCCCCCCcCCC	!!!!!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	308	N	17	ttttttTTTTTTTtTTT	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	309	N	17	ggggggGGGGGGGgGGG	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	310	N	17	g$g$ggggGGTGGGGgGGG	!!!!!!!!!!!!!!!!!
comp115911_c0_seq1	311	N	15	aaaaAAAAAAAaAAA	!!!!!!!!!!!!!!!
comp115911_c0_seq1	312	N	15	a$aaaAAAAAAAaAAA	!!!!!!!!!!!!!!!
comp115911_c0_seq1	313	N	14	aaaAAAAAAAaAAA	!!!!!!!!!!!!!!
comp115911_c0_seq1	314	N	14	tttTTTTTTTtTTT	!!!!!!!!!!!!!!
comp115911_c0_seq1	315	N	14	cccCCCCCCCcCCC	!!!!!!!!!!!!!!
comp115911_c0_seq1	316	N	14	cccCCCCCCCcCCC	!!!!!!!!!!!!!!
comp115911_c0_seq1	317	N	14	g$ggGGGGGGGgGGG	!!!!!!!!!!!!!!
comp115911_c0_seq1	318	N	13	a$aAAAAAAAaCAA	!!!!!!!!!!!!!
comp115911_c0_seq1	319	N	12	aAAAAAAAaAAA	!!!!!!!!!!!!
comp115911_c0_seq1	320	N	12	cCCCCCCCcCCC	!!!!!!!!!!!!
comp115911_c0_seq1	321	N	12	a$TTTTTTTtTTT	!!!!!!!!!!!!
comp115911_c0_seq1	322	N	11	GGGGGGGgGGG	!!!!!!!!!!!
comp115911_c0_seq1	323	N	11	AAAAAAAaAAA	!!!!!!!!!!!
comp115911_c0_seq1	324	N	11	TTTTTTTtTTT	!!!!!!!!!!!
comp115911_c0_seq1	325	N	11	G$G$G$G$G$GGgGGG	!!!!!!!!!!!
comp115911_c0_seq1	326	N	6	A$A$aAAA	!!!!!!
comp115911_c0_seq1	327	N	4	cCCC	!!!!
comp115911_c0_seq1	328	N	4	a$TTT	!!!!
comp115911_c0_seq1	329	N	3	TTT	!!!
comp115911_c0_seq1	330	N	3	GGG	!!!
comp115911_c0_seq1	331	N	3	TTT	!!!
comp115911_c0_seq1	332	N	3	T$TT	!!!
comp115911_c0_seq1	333	N	2	TT	!!
comp115911_c0_seq1	334	N	2	CC	!!
comp115911_c0_seq1	335	N	2	AA	!!
comp115911_c0_seq1	336	N	2	TT	!!
comp115911_c0_seq1	337	N	2	CC	!!
comp115911_c0_seq1	338	N	2	AA	!!
comp115911_c0_seq1	339	N	2	AA	!!
comp115911_c0_seq1	340	N	2	TT	!!
comp115911_c0_seq1	341	N	2	T$T	!!
comp115911_c0_seq1	342	N	1	T	!
comp115911_c0_seq1	343	N	1	C	!
comp115911_c0_seq1	344	N	1	G	!
comp115911_c0_seq1	345	N	1	A	!
comp115911_c0_seq1	346	N	1	C	!
comp115911_c0_seq1	347	N	1	T	!
comp115911_c0_seq1	348	N	1	T	!
comp115911_c0_seq1	349	N	1	T$	!
comp115911_c0_seq1	394	N	1	^]t	!
comp115911_c0_seq1	395	N	9	g^]g^>g^]g^]g^]g^]g^]g^]g	!!!!!!!!!
comp115911_c0_seq1	396	N	10	aaaaaaaaa^]a	!!!!!!!!!!
comp115911_c0_seq1	397	N	11	aaaaaaaaaa^>a	!!!!!!!!!!!
comp115911_c0_seq1	398	N	11	ggggggggggg	!!!!!!!!!!!
comp115911_c0_seq1	399	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	400	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	401	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	402	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	403	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	404	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	405	N	11	ccccccccccc	!!!!!!!!!!!
comp115911_c0_seq1	406	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	407	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	408	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	409	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	410	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	411	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	412	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	413	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	414	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	415	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	416	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	417	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	418	N	11	ggggggggggg	!!!!!!!!!!!
comp115911_c0_seq1	419	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	420	N	11	ggggggggggg	!!!!!!!!!!!
comp115911_c0_seq1	421	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	422	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	423	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	424	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	425	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	426	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	427	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	428	N	11	ggggggggggg	!!!!!!!!!!!
comp115911_c0_seq1	429	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	430	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	431	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	432	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	433	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	434	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	435	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	436	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	437	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	438	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	439	N	11	ggggggggggg	!!!!!!!!!!!
comp115911_c0_seq1	440	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	441	N	11	aaaaaaaaaaa	!!!!!!!!!!!
comp115911_c0_seq1	442	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	443	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	444	N	11	ccccccccccc	!!!!!!!!!!!
comp115911_c0_seq1	445	N	11	ggggggggggg	!!!!!!!!!!!
comp115911_c0_seq1	446	N	11	ttttttttttt	!!!!!!!!!!!
comp115911_c0_seq1	447	N	11	g$ggg$ggggggg$	!!!!!!!!!!!
comp115911_c0_seq1	448	N	8	a$a$a$a$a$a$a$g$	!!!!!!!!
