comp115911_c0_seq1	39	N	1	^]T	f	]
comp115911_c0_seq1	40	N	1	T	f	]
comp115911_c0_seq1	41	N	2	G^]G	fh	]]
comp115911_c0_seq1	42	N	2	GG	fh	]]
comp115911_c0_seq1	43	N	3	AA^]T	eh!	]]]
comp115911_c0_seq1	44	N	4	CCC^]C	fh!!	]]]]
comp115911_c0_seq1	45	N	4	AAAA	fh!!	]]]]
comp115911_c0_seq1	46	N	5	AAAA^]T	eh!!!	]]]]]
comp115911_c0_seq1	47	N	10	CCCCC^]C^>C^]T^]T^]T	fh!!!!!!!!	]]]]]]>]]]
comp115911_c0_seq1	48	N	12	TTTTTTTTTT^]T^]T	fh!!!!!!!!!!	]]]]]]>]]]]]
comp115911_c0_seq1	49	N	13	GGGGGGGGGGGG^]G	eh!!!!!!!!!!!	]]]]]]>]]]]]]
comp115911_c0_seq1	50	N	13	AAAAAAAAAAAAA	fg!!!!!!!!!!!	]]]]]]>]]]]]]
comp115911_c0_seq1	51	N	13	CCCCCCCCCCCCC	fh!!!!!!!!!!!	]]]]]]>]]]]]]
comp115911_c0_seq1	52	N	13	GGGGGGGGGGGGG	fh!!!!!!!!!!!	]]]]]]>]]]]]]
comp115911_c0_seq1	53	N	13	GGGGGGGGGGGGG	fh!!!!!!!!!!!	]]]]]]>]]]]]]
comp115911_c0_seq1	54	N	13	AAAAAAAAAAAAA	eh!!!!!!!!!!!	]]]]]]>]]]]]]
comp115911_c0_seq1	55	N	13	TTTTTTTTTTTTT	fh!!!!!!!!!!!	]]]]]]>]]]]]]
comp115911_c0_seq1	56	N	13	TTTTTTTTTTTTT	ff!!!!!!!!!!!	]]]]]]>]]]]]]
comp115911_c0_seq1	57	N	13	AAAAAAAAAAAAA	dh!!!!!!!!!!!	]]]]]]>]]]]]]
comp115911_c0_seq1	58	N	13	AAAAAAAAAAAAA	eh!!!!!!!!!!!	]]]]]]>]]]]]]
comp115911_c0_seq1	59	N	15	CCCCCCCCCCCCC^]T^]C	fh!!!!!!!!!!!!!	]]]]]]>]]]]]]]]
comp115911_c0_seq1	60	N	15	GGGGGGGGGGGGGGG	fh!!!!!!!!!!!!!	]]]]]]>]]]]]]]]
comp115911_c0_seq1	61	N	15	TTTTTTTTTTTTTTT	fh!!!!!!!!!!!!!	]]]]]]>]]]]]]]]
comp115911_c0_seq1	62	N	15	GGGGGGGGGGGGGGG	fh!!!!!!!!!!!!!	]]]]]]>]]]]]]]]
comp115911_c0_seq1	63	N	15	AAAAAAAAAAAAAAA	fg!!!!!!!!!!!!!	]]]]]]>]]]]]]]]
comp115911_c0_seq1	64	N	15	TTTTTTTTTTTTTTT	fg!!!!!!!!!!!!!	]]]]]]>]]]]]]]]
comp115911_c0_seq1	65	N	17	CCCCCCCCCCCCCCC^>C^]c	fh!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]
comp115911_c0_seq1	66	N	19	CCCCCCCCCCCCCCCCc^]T^]T	fh!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]
comp115911_c0_seq1	67	N	19	CCCCCCCCCCCCCCCCcCC	fh!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]
comp115911_c0_seq1	68	N	19	GGGGGGGGGGGGGGGGgGG	fh!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]
comp115911_c0_seq1	69	N	20	CCCCCCCCCCCCCCCCcCC^]C	fh!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	70	N	20	GGGGGGGGGGGGGGGGgGGG	fh!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	71	N	20	GGGGGGGGGGGGGGGGgGGG	fh!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	72	N	20	AAAAAAAAAAAAAAAAaAAA	ef!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	73	N	20	TTTTTTTTTTTTTTTTtTTT	fh!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	74	N	20	TTTTTTTTTTTTTTTTtTTT	fh!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	75	N	20	AAAAAAAAAAAAAAAAaAAA	eg!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	76	N	20	AAAAAAAAAAAAAAAAaAAA	df!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	77	N	20	TTTTTTTTTTTTTTTTtTTT	ff!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	78	N	20	AAAAAAAAAAAAAAAAaAAA	fh!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	79	N	20	GGGGGGGGGGGGGGGGgGGG	fh!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	80	N	21	TTTTTTTTTTTTTTTTtTTT^]T	fd!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]
comp115911_c0_seq1	81	N	21	GGGGGGGGGGGGGGGGgGGGG	fd!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]
comp115911_c0_seq1	82	N	21	GGGGGGGGGGGGGGGGgGGGG	fh!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]
comp115911_c0_seq1	83	N	21	TTTTTTTTTTTTTTTTtTTTT	dd!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]
comp115911_c0_seq1	84	N	21	GGGGGGGGGGGGGGGGgGGGG	fh!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]
comp115911_c0_seq1	85	N	22	TTTTTTTTTTTTTTTTtTTTT^]T	fg!!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]]
comp115911_c0_seq1	86	N	22	AAAAAAAAAAAAAAAAaAAAAA	ec!!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]]
comp115911_c0_seq1	87	N	23	TTTTTTTTTTTTTTTTtTTTTT^]T	fh!!!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]]]
comp115911_c0_seq1	88	N	25	AAAAAAAAAAAAAAAAaAAAAAA^]A^]A	de!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]]]]]
comp115911_c0_seq1	89	N	25	AAAAAAAAAAAAAAAAaAAAAAAAA	fg!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]]]]]
comp115911_c0_seq1	90	N	25	AAAAAAAAAAAAAAAAaAAAAAAAA	cg!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]]]]]
comp115911_c0_seq1	91	N	25	AAAAAAAAAAAAAAAAaAAAAAAAA	fh!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]]]]]
comp115911_c0_seq1	92	N	25	A$AAAAAAAAAAAAAAAaAAAAAAAA	fg!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]>]]]]]]]]]
comp115911_c0_seq1	93	N	24	A$AAAAAAAAAAAAAAaAAAAAAAA	g!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]]]>]]]]]]]]]
comp115911_c0_seq1	94	N	23	CCCCCCCCCCCCCCcCCCCCCCC	!!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]]]]]]]>]]]]]]]]]
comp115911_c0_seq1	95	N	23	GGGGGGGGGGGGGGgGGGGGGGG	!!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]]]]]]]>]]]]]]]]]
comp115911_c0_seq1	96	N	23	A$A$AAAAAAAAAAAAaAAAAAAAA	!!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]]]]]]]>]]]]]]]]]
comp115911_c0_seq1	97	N	22	TTTTTTTTTTTTtTTTTTTTT^]t	!!!!!!!!!!!!!!!!!!!!!!	]]>]]]]]]]]>]]]]]]]]]]
comp115911_c0_seq1	98	N	22	TTTTTTTTTTTTtTTTTTTTTt	!!!!!!!!!!!!!!!!!!!!!!	]]>]]]]]]]]>]]]]]]]]]]
comp115911_c0_seq1	99	N	22	T$T$T$TTTTTTTTTtTTTTTTTTt	!!!!!!!!!!!!!!!!!!!!!!	]]>]]]]]]]]>]]]]]]]]]]
comp115911_c0_seq1	100	N	19	T$T$T$TT$TTTTtTTTTTTTTt	!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]]]]]]
comp115911_c0_seq1	101	N	15	A$A$AAAaAAAAAAAAa	!!!!!!!!!!!!!!!	]]]]>]]]]]]]]]]
comp115911_c0_seq1	102	N	13	AAAaAAAAAAAAa	!!!!!!!!!!!!!	]]>]]]]]]]]]]
comp115911_c0_seq1	103	N	13	AAAaAAAAAAAAa	!!!!!!!!!!!!!	]]>]]]]]]]]]]
comp115911_c0_seq1	104	N	13	CCCcCCCCCCCCc	!!!!!!!!!!!!!	]]>]]]]]]]]]]
comp115911_c0_seq1	105	N	13	AAAaAAAAAAAAa	!!!!!!!!!!!!!	]]>]]]]]]]]]]
comp115911_c0_seq1	106	N	13	CCCcCCCCCCCCc	!!!!!!!!!!!!!	]]>]]]]]]]]]]
comp115911_c0_seq1	107	N	13	GGGgGGGGGGGGg	!!!!!!!!!!!!!	]]>]]]]]]]]]]
comp115911_c0_seq1	108	N	13	AAAaAAAAAAAAa	!!!!!!!!!!!!!	]]>]]]]]]]]]]
comp115911_c0_seq1	109	N	13	TTTtTTTTTTTTt	!!!!!!!!!!!!!	]]>]]]]]]]]]]
comp115911_c0_seq1	110	N	13	GGGgGGGGGGGGg	!!!!!!!!!!!!!	]]>]]]]]]]]]]
comp115911_c0_seq1	111	N	13	TT$TtTTTTTTTTt	!!!!!!!!!!!!!	]]>]]]]]]]]]]
comp115911_c0_seq1	112	N	12	A$AaAAAAAAAAa	!!!!!!!!!!!!	]>]]]]]]]]]]
comp115911_c0_seq1	113	N	11	TtTTTTTTTTt	!!!!!!!!!!!	>]]]]]]]]]]
comp115911_c0_seq1	114	N	11	GgGGGGGGGGg	!!!!!!!!!!!	>]]]]]]]]]]
comp115911_c0_seq1	115	N	11	TtTTTTTTTTt	!!!!!!!!!!!	>]]]]]]]]]]
comp115911_c0_seq1	116	N	12	TaAAAAAAAAa^]T	!!!!!!!!!!!!	>]]]]]]]]]]]
comp115911_c0_seq1	117	N	13	G$g$GGGGGGGGgG^]T	!!!!!!!!!!!!!	>]]]]]]]]]]]]
comp115911_c0_seq1	118	N	12	AAAAAAAAaAA^]a	!!!!!!!!!!!!	]]]]]]]]]]]]
comp115911_c0_seq1	119	N	12	A$A$AAAAAAaAAa	!!!!!!!!!!!!	]]]]]]]]]]]]
comp115911_c0_seq1	120	N	10	AAAAAAaAAa	!!!!!!!!!!	]]]]]]]]]]
comp115911_c0_seq1	121	N	10	T$TTTTTtTTt	!!!!!!!!!!	]]]]]]]]]]
comp115911_c0_seq1	122	N	9	AAAAAaAAa	!!!!!!!!!	]]]]]]]]]
comp115911_c0_seq1	123	N	9	AAAAAaAAa	!!!!!!!!!	]]]]]]]]]
comp115911_c0_seq1	124	N	9	TTTTTtTTt	!!!!!!!!!	]]]]]]]]]
comp115911_c0_seq1	125	N	9	AAAAAaAAa	!!!!!!!!!	]]]]]]]]]
comp115911_c0_seq1	126	N	9	TTTTTtTTt	!!!!!!!!!	]]]]]]]]]
comp115911_c0_seq1	127	N	9	AAAAAaAAa	!!!!!!!!!	]]]]]]]]]
comp115911_c0_seq1	128	N	10	TTTTTtTTt^]T	!!!!!!!!!!	]]]]]]]]]]
comp115911_c0_seq1	129	N	10	TTTTTtTTtT	!!!!!!!!!!	]]]]]]]]]]
comp115911_c0_seq1	130	N	11	CCCCCcCCcC^]c	!!!!!!!!!!!	]]]]]]]]]]]
comp115911_c0_seq1	131	N	11	TTTTTtTTtTt	!!!!!!!!!!!	]]]]]]]]]]]
comp115911_c0_seq1	132	N	11	TTTTTtTTtTt	!!!!!!!!!!!	]]]]]]]]]]]
comp115911_c0_seq1	133	N	11	T$TTTTtTTtTt	!!!!!!!!!!!	]]]]]]]]]]]
comp115911_c0_seq1	134	N	10	AAAAaAAaAa	!!!!!!!!!!	]]]]]]]]]]
comp115911_c0_seq1	135	N	10	TTTTtTTtTt	!!!!!!!!!!	]]]]]]]]]]
comp115911_c0_seq1	136	N	10	AAAAaAAaAa	!!!!!!!!!!	]]]]]]]]]]
comp115911_c0_seq1	137	N	10	CCCCcCCcCc	!!!!!!!!!!	]]]]]]]]]]
comp115911_c0_seq1	138	N	10	A$AAAaAAaAa	!!!!!!!!!!	]]]]]]]]]]
comp115911_c0_seq1	139	N	10	T$TTtTTtTt^]T	!!!!!!!!!!	]]]]]]]]]]
comp115911_c0_seq1	140	N	9	A$A$aAAaAaA	!!!!!!!!!	]]]]]]]]]
comp115911_c0_seq1	141	N	7	aAAaAaA	!!!!!!!	]]]]]]]
comp115911_c0_seq1	142	N	7	tTTtTtT	!!!!!!!	]]]]]]]
comp115911_c0_seq1	143	N	7	aAAaAaA	!!!!!!!	]]]]]]]
comp115911_c0_seq1	144	N	7	tTTtTtT	!!!!!!!	]]]]]]]
comp115911_c0_seq1	145	N	7	aAAaAaA	!!!!!!!	]]]]]]]
comp115911_c0_seq1	146	N	7	tTTtTtT	!!!!!!!	]]]]]]]
comp115911_c0_seq1	147	N	7	aAAaAaA	!!!!!!!	]]]]]]]
comp115911_c0_seq1	148	N	7	tTTtTtT	!!!!!!!	]]]]]]]
comp115911_c0_seq1	149	N	7	a$AAaAaA	!!!!!!!	]]]]]]]
comp115911_c0_seq1	150	N	6	AAaAaA	!!!!!!	]]]]]]
comp115911_c0_seq1	151	N	6	TTtTtT	!!!!!!	]]]]]]
comp115911_c0_seq1	152	N	6	AAaAaA	!!!!!!	]]]]]]
comp115911_c0_seq1	153	N	6	TTtTtT	!!!!!!	]]]]]]
comp115911_c0_seq1	154	N	6	AAaAaA	!!!!!!	]]]]]]
comp115911_c0_seq1	155	N	7	TTtTtT^]t	!!!!!!!	]]]]]]]
comp115911_c0_seq1	156	N	7	TTtTtTt	!!!!!!!	]]]]]]]
comp115911_c0_seq1	157	N	7	AAaAaAa	!!!!!!!	]]]]]]]
comp115911_c0_seq1	158	N	7	TTtTtTt	!!!!!!!	]]]]]]]
comp115911_c0_seq1	159	N	7	GGgGgGg	!!!!!!!	]]]]]]]
comp115911_c0_seq1	160	N	8	TTtTtTt^]T	!!!!!!!!	]]]]]]]]
comp115911_c0_seq1	161	N	8	GGgGgGgG	!!!!!!!!	]]]]]]]]
comp115911_c0_seq1	162	N	8	TTtTtTtT	!!!!!!!!	]]]]]]]]
comp115911_c0_seq1	163	N	8	AAaAaAaA	!!!!!!!!	]]]]]]]]
comp115911_c0_seq1	164	N	8	TTtTtTtT	!!!!!!!!	]]]]]]]]
comp115911_c0_seq1	165	N	8	TTtTtTtT	!!!!!!!!	]]]]]]]]
comp115911_c0_seq1	166	N	8	AAaAaAaA	!!!!!!!!	]]]]]]]]
comp115911_c0_seq1	167	N	8	TTtTtTtT	!!!!!!!!	]]]]]]]]
comp115911_c0_seq1	168	N	11	CCcCcCcC^]C^]T^]T	!!!!!!!!!!!	]]]]]]]]]]]
comp115911_c0_seq1	169	N	12	A$AaAaAaAAAA^>A	!!!!!!!!!!!!	]]]]]]]]]]]>
comp115911_c0_seq1	170	N	11	T$c$TtTtTTTTT	!!!!!!!!!!!	]]]]]]]]]]>
comp115911_c0_seq1	171	N	10	CcCcCCCCC^]C	!!!!!!!!!!	]]]]]]]]>]
comp115911_c0_seq1	172	N	11	GgGgGGGGGG^]G	!!!!!!!!!!!	]]]]]]]]>]]
comp115911_c0_seq1	173	N	11	CcCcCCCCCCC	!!!!!!!!!!!	]]]]]]]]>]]
comp115911_c0_seq1	174	N	11	AaAaAAAAAAA	!!!!!!!!!!!	]]]]]]]]>]]
comp115911_c0_seq1	175	N	11	TtTtTTTTTTT	!!!!!!!!!!!	]]]]]]]]>]]
comp115911_c0_seq1	176	N	11	TtTtTTTTTTT	!!!!!!!!!!!	]]]]]]]]>]]
comp115911_c0_seq1	177	N	11	TtTtTTTTTTT	!!!!!!!!!!!	]]]]]]]]>]]
comp115911_c0_seq1	178	N	12	TtTtTTTTTTT^>T	!!!!!!!!!!!!	]]]]]]]]>]]>
comp115911_c0_seq1	179	N	12	CcCcCCCCCCCC	!!!!!!!!!!!!	]]]]]]]]>]]>
comp115911_c0_seq1	180	N	13	GgGgGGGGGGGG^>G	!!!!!!!!!!!!!	]]]]]]]]>]]>>
comp115911_c0_seq1	181	N	14	A$aAaAAAAAAAAA^]T	!!!!!!!!!!!!!!	]]]]]]]]>]]>>]
comp115911_c0_seq1	182	N	13	c$CcCCCCCCCCCC	!!!!!!!!!!!!!	]]]]]]]>]]>>]
comp115911_c0_seq1	183	N	12	AaAAAAAAAAGA	!!!!!!!!!!!!	]]]]]]>]]>>]
comp115911_c0_seq1	184	N	12	AaAAAAAAAAAA	!!!!!!!!!!!!	]]]]]]>]]>>]
comp115911_c0_seq1	185	N	14	GgGGGGGGGGAG^>G^]g	!!!!!!!!!!!!!!	]]]]]]>]]>>]>]
comp115911_c0_seq1	186	N	14	TtTTTTTTTTTTTt	!!!!!!!!!!!!!!	]]]]]]>]]>>]>]
comp115911_c0_seq1	187	N	14	TtTTTTTTTTTTTt	!!!!!!!!!!!!!!	]]]]]]>]]>>]>]
comp115911_c0_seq1	188	N	16	TtTTTTTTTTTTTt^]T^]t	!!!!!!!!!!!!!!!!	]]]]]]>]]>>]>]]]
comp115911_c0_seq1	189	N	16	TtTTTTTTTTTTTtTt	!!!!!!!!!!!!!!!!	]]]]]]>]]>>]>]]]
comp115911_c0_seq1	190	N	16	TtTTTTTTTTTTTtTt	!!!!!!!!!!!!!!!!	]]]]]]>]]>>]>]]]
comp115911_c0_seq1	191	N	16	TtTTTTTTTTTTTtTt	!!!!!!!!!!!!!!!!	]]]]]]>]]>>]>]]]
comp115911_c0_seq1	192	N	16	G$gGGGGGGGGGGGgGg	!!!!!!!!!!!!!!!!	]]]]]]>]]>>]>]]]
comp115911_c0_seq1	193	N	15	tTTTTTTTTTTTtTt	!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]
comp115911_c0_seq1	194	N	16	tTTTTTTTTTTTtTt^]t	!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]
comp115911_c0_seq1	195	N	16	aAAAAAAAAAAAaAaa	!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]
comp115911_c0_seq1	196	N	17	tTTTTTTTTTTTtTtt^]t	!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]
comp115911_c0_seq1	197	N	19	gGGGGGGGGGGGgGggg^]g^]g	!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]
comp115911_c0_seq1	198	N	19	cCCCCCCCCCCCcCccccc	!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]
comp115911_c0_seq1	199	N	23	tTTTTTTTTTTTtTttttt^]t^]t^]T^]t	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]]]]]
comp115911_c0_seq1	200	N	23	cCCCCCCCCCCCcCcccctccCc	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]]]]]
comp115911_c0_seq1	201	N	23	tTTTTTTTTTTTtTtttttttTt	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]]]]]
comp115911_c0_seq1	202	N	23	tTTTTTTTTTTTtTtttttttTt	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]]]]]
comp115911_c0_seq1	203	N	24	tTTTTTTTTTTTtTtttttttTt^>t	!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]]]]]>
comp115911_c0_seq1	204	N	24	cCCCCCCCCCCCcCcccccccCcc	!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]]]]]>
comp115911_c0_seq1	205	N	24	aAAAAAAAAAAAaAaaaaaaaAaa	!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]]]]]>
comp115911_c0_seq1	206	N	24	tTTTTTTTTTTTtTtttttttTtt	!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]]]]]>
comp115911_c0_seq1	207	N	24	gGAGGGGGGGAGaGgggggggGag	!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]]]]]>
comp115911_c0_seq1	208	N	24	a$TTTTTTTTTTTtTtttttttTtt	!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]>>]>]]]]]]]]]]]>
comp115911_c0_seq1	209	N	23	TTTTTTTTTTTtTtttttttTtt	!!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]>>]>]]]]]]]]]]]>
comp115911_c0_seq1	210	N	23	AAAAAAAAAAAaAaaaaaaaAaa	!!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]>>]>]]]]]]]]]]]>
comp115911_c0_seq1	211	N	23	TTTTTTTTTTTtTtttttttTtg	!!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]>>]>]]]]]]]]]]]>
comp115911_c0_seq1	212	N	23	GGGGGGGGGGGgGgggggggGgg	!!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]>>]>]]]]]]]]]]]>
comp115911_c0_seq1	213	N	23	A$AAAAAAAAAAaAaaaaaaaAaa	!!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]>>]>]]]]]]]]]]]>
comp115911_c0_seq1	214	N	23	TTTTTTTTTTtTtttttttTtt^]t	!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]>>]>]]]]]]]]]]]>]
comp115911_c0_seq1	215	N	23	GGGGGGGGGGgGgggggggGgtg	!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]>>]>]]]]]]]]]]]>]
comp115911_c0_seq1	216	N	25	TTTTTTGTTTtTtttttttTttt^]t^]t	!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]>>]>]]]]]]]]]]]>]]]
comp115911_c0_seq1	217	N	26	TTTTTTTTTTtTtttttttTttttt^]T	!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]>>]>]]]]]]]]]]]>]]]]
comp115911_c0_seq1	218	N	26	TTTTTTATTTtTtttttttTtttttT	!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]>>]>]]]]]]]]]]]>]]]]
comp115911_c0_seq1	219	N	27	AAAAAAA+2ATAAAaAaaaaaaaAaaaaaA^]a	!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]>>]>]]]]]]]]]]]>]]]]]
comp115911_c0_seq1	220	N	28	T$TTTTTTTTTtTtttttttTtgtttTt^]T	!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]>>]>]]]]]]]]]]]>]]]]]]
comp115911_c0_seq1	221	N	29	G$G$G$GGGGGGgGgggggggGgggggGgG^]g^]g	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]>]]>>]>]]]]]]]]]]]>]]]]]]]]
comp115911_c0_seq1	222	N	27	CCCCCCcCcccccccCcccccCcCcc^>c	!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]>>]>]]]]]]]]]]]>]]]]]]]]>
comp115911_c0_seq1	223	N	27	T$TATTTtTtttttttTtttttTtTttt	!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]>>]>]]]]]]]]]]]>]]]]]]]]>
comp115911_c0_seq1	224	N	26	A$AAAAaAaaaaaaaAaaaaaAaAaaa	!!!!!!!!!!!!!!!!!!!!!!!!!!	]>>]>]]]]]]]]]]]>]]]]]]]]>
comp115911_c0_seq1	225	N	25	TT$TTtTtttttttTtttttTtTttt	!!!!!!!!!!!!!!!!!!!!!!!!!	>>]>]]]]]]]]]]]>]]]]]]]]>
comp115911_c0_seq1	226	N	24	TTTtTtttttttTtt+1atttTtTttt	!!!!!!!!!!!!!!!!!!!!!!!!	>]>]]]]]]]]]]]>]]]]]]]]>
comp115911_c0_seq1	227	N	24	AAAaAaaaaaaaAaaaaaAaAaaa	!!!!!!!!!!!!!!!!!!!!!!!!	>]>]]]]]]]]]]]>]]]]]]]]>
comp115911_c0_seq1	228	N	24	A$AAaAaaaaaaaAaaaaaAaAaaa	!!!!!!!!!!!!!!!!!!!!!!!!	>]>]]]]]]]]]]]>]]]]]]]]>
comp115911_c0_seq1	229	N	23	AAaAaaaaaaaAaaaaaAaAaaa	!!!!!!!!!!!!!!!!!!!!!!!	]>]]]]]]]]]]]>]]]]]]]]>
comp115911_c0_seq1	230	N	23	TTtTtttttttTtttttTtTttt	!!!!!!!!!!!!!!!!!!!!!!!	]>]]]]]]]]]]]>]]]]]]]]>
comp115911_c0_seq1	231	N	23	AAaAaaaaaaaAaa-1naaaAaAaat	!!!!!!!!!!!!!!!!!!!!!!!	]>]]]]]]]]]]]>]]]]]]]]>
comp115911_c0_seq1	232	N	23	TTtTtttttttTt*tttTtTttt	!!!!!!!!!!!!!!!!!!!!!!!	]>]]]]]]]]]]]>]]]]]]]]>
comp115911_c0_seq1	233	N	24	AAaAaaaataaAaaaaaAaAgaa^]T	!!!!!!!!!!!!!!!!!!!!!!!!	]>]]]]]]]]]]]>]]]]]]]]>]
comp115911_c0_seq1	234	N	25	G$GgGggtggggGgggggGgGggcG^]G	!!!!!!!!!!!!!!!!!!!!!!!!!	]>]]]]]]]]]]]>]]]]]]]]>]]
comp115911_c0_seq1	235	N	24	TtTtttttttTtttttTtTtttTT	!!!!!!!!!!!!!!!!!!!!!!!!	>]]]]]]]]]]]>]]]]]]]]>]]
comp115911_c0_seq1	236	N	24	TtTtttttttTtttttTtTtttTT	!!!!!!!!!!!!!!!!!!!!!!!!	>]]]]]]]]]]]>]]]]]]]]>]]
comp115911_c0_seq1	237	N	25	G$g$GgggggggGgggggGgGacaGG^]T	!!!!!!!!!!!!!!!!!!!!!!!!!	>]]]]]]]]]]]>]]]]]]]]>]]]
comp115911_c0_seq1	238	N	23	AaaaaaaaAaaaaaAaAaaaAAA	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]]]>]]]]]]]]>]]]
comp115911_c0_seq1	239	N	23	AaaaaaaaAaaaaaAaAaaaAAA	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]]]>]]]]]]]]>]]]
comp115911_c0_seq1	240	N	23	A$a$aaataaAaaaaaAaAaaaAAA	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]]]>]]]]]]]]>]]]
comp115911_c0_seq1	241	N	21	ttttttTtttttTtTttcTTT	!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]]]]>]]]
comp115911_c0_seq1	242	N	21	aaaaaaAagaaaAaAaaaAAA	!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]]]]>]]]
comp115911_c0_seq1	243	N	22	ggggggGgggggGgGgggGGG^]G	!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]]]]>]]]]
comp115911_c0_seq1	244	N	23	ccccccCcccccCcCcccCCCC^]C	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]]]]>]]]]]
comp115911_c0_seq1	245	N	23	ccccccCcccccCcCcccCCCCC	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]]]]>]]]]]
comp115911_c0_seq1	246	N	23	ggggggGgggggGgGgggGGGGG	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]]]]>]]]]]
comp115911_c0_seq1	247	N	23	a$aaaaaAaaaaaAaAaaaAAAAA	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]]]]>]]]]]
comp115911_c0_seq1	248	N	23	cccccCcccccCcCcccCCCCC^>c	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]>]]]]]]]]>]]]]]>
comp115911_c0_seq1	249	N	23	a$g$gggGgggggGgGggaGGGGGg	!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]>]]]]]]]]>]]]]]>
comp115911_c0_seq1	250	N	21	a$aaAaaaaaAaAaagAAAAAa	!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]]]>]]]]]>
comp115911_c0_seq1	251	N	22	c$c$Cc$ccccCcCcccCCCCCc^]C^]C	!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]]]]]]]>]]]]]>]]
comp115911_c0_seq1	252	N	20	G$ggggGgGgggGGGGGgGG^]g	!!!!!!!!!!!!!!!!!!!!	]>]]]]]]]]>]]]]]>]]]
comp115911_c0_seq1	253	N	19	aaaaAaAaaaAAAAAaAAa	!!!!!!!!!!!!!!!!!!!	>]]]]]]]]>]]]]]>]]]
comp115911_c0_seq1	254	N	19	aaaaAaAaaaAAAAAaAAa	!!!!!!!!!!!!!!!!!!!	>]]]]]]]]>]]]]]>]]]
comp115911_c0_seq1	255	N	20	ggggGgGgggGGGGGgGGg^]T	!!!!!!!!!!!!!!!!!!!!	>]]]]]]]]>]]]]]>]]]]
comp115911_c0_seq1	256	N	21	a$aaaAaAaaaAAAAAaAAaA^]T	!!!!!!!!!!!!!!!!!!!!!	>]]]]]]]]>]]]]]>]]]]]
comp115911_c0_seq1	257	N	21	cccCcCcccCCCCCcCCcCC^]C	!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]>]]]]]]
comp115911_c0_seq1	258	N	21	gggGgGggaGGGGGgGGgGGG	!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]>]]]]]]
comp115911_c0_seq1	259	N	24	aaaAaAaaaAAAAAaAAaAAA^>T^]T^]a	!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]>]]]]]]>]]
comp115911_c0_seq1	260	N	25	aaaAaAaaaAAAAAaAAaAAAAAa^]A	!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]>]]]]]]>]]]
comp115911_c0_seq1	261	N	27	tttTtTtttTTTTTtTTtTTTTTtT^]t^]t	!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]>]]]]]]>]]]]]
comp115911_c0_seq1	262	N	27	tttTtTtttTTTTTtTTtTTTTTtTtt	!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]>]]]]]]>]]]]]
comp115911_c0_seq1	263	N	27	tttTtTtttTTTTTtTTtTTTTTtTtt	!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]>]]]]]]>]]]]]
comp115911_c0_seq1	264	N	28	tttTtTtttTTTTTtTTtTTTTTtTtt^]t	!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]>]]]]]]>]]]]]]
comp115911_c0_seq1	265	N	30	cccCcCcccCCCCCcCCcCCCCCcCccc^]c^]c	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]>]]]]]]>]]]]]]]]
comp115911_c0_seq1	266	N	31	tttTtTtttTTTTTtTTtTTTTTtTttttt^]t	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]>]]]]]]>]]]]]]]]]
comp115911_c0_seq1	267	N	33	a$ggGgGgggGGGGGgGGgGGGGGgGgggggg^]g^]g	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]]>]]]]]]>]]]]]]]]]]]
comp115911_c0_seq1	268	N	37	g$gGgGgggGGGGGgGGgGGGGGgGgggggggg^>g^]g^]g^]g^]g	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]]>]]]]]>]]]]]]>]]]]]]]]]]]>]]]]
comp115911_c0_seq1	269	N	36	a$A$aAaaaAAAAAaAAaAAAAAaAaaaaaaaaaaaaa	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]>]]]]]]>]]]]]]]]]]]>]]]]
comp115911_c0_seq1	270	N	34	gGgggGGGGGgGGgGGGGGgGggggggggggggg	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]]]]>]]]]]]>]]]]]]]]]]]>]]]]
comp115911_c0_seq1	271	N	34	c$CcccCCCCCcCCcCCCCCcCccccccccccccc	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]]]]>]]]]]]>]]]]]]]]]]]>]]]]
comp115911_c0_seq1	272	N	33	AaaaAAAAAaAAaAAAAAaAaaaaaaaaaaaaa	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]]]]>]]]]]]>]]]]]]]]]]]>]]]]
comp115911_c0_seq1	273	N	34	G$gg$gGGGGGgGGgGGGGGgGggggggggggggg^>T	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>
comp115911_c0_seq1	274	N	34	a$a$AAAAAaAAaAAAAAaAaaaaaaaaaaaaaA^]T^]A	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]>]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]
comp115911_c0_seq1	275	N	32	TTTTTtTTtTTTTTtTtttttttttttttTTT	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]
comp115911_c0_seq1	276	N	32	GGGGGgGGgGGGGGgGgggggggggggggGGG	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]
comp115911_c0_seq1	277	N	32	AAAAAaAAaAAAAAaAaaaaaaaaaaaaaAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]
comp115911_c0_seq1	278	N	32	AAAAAaAAaAAAAAaAaaaaaaaaaaaaaAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]
comp115911_c0_seq1	279	N	32	CCCCCcCCcCCCCCcCcccccccccccccCCC	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]
comp115911_c0_seq1	280	N	32	TTTTTtTTtTTTTTtTtttttttttttttTTT	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]
comp115911_c0_seq1	281	N	32	TAAAAaAAaAAAAAaAaaaagaaaaaaaaAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]
comp115911_c0_seq1	282	N	32	TTTTTtTTtTTTTTtTtttttttttttttTTT	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]
comp115911_c0_seq1	283	N	32	AAAAAaAAaAAAAAaAaaaaaaaaaaaaaAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]
comp115911_c0_seq1	284	N	33	GGGGGgGGgGGGGGgGgggggggggggggGGG^]G	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]
comp115911_c0_seq1	285	N	33	AAAAAaAAaAAAAAaAaaaaaaaaaaaaaAAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]
comp115911_c0_seq1	286	N	33	T$T$TTTtTTtTTTTTtTtttttttttttttTTTT	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]
comp115911_c0_seq1	287	N	31	CCCcCCcCCCCCcCcccccccccccccCCCC	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]
comp115911_c0_seq1	288	N	31	TTTtTTtTTTTTtTtttttttttttttTTTT	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]
comp115911_c0_seq1	289	N	32	GGGgGGgGGGGGgGgggggggggggggGGGG^]T	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]]
comp115911_c0_seq1	290	N	32	T$TTtTTtTTTTTtTtttttttttttttTTTTT	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]]
comp115911_c0_seq1	291	N	31	GGgGGgGGGGGgGgggggggggggggGGGGG	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]]
comp115911_c0_seq1	292	N	31	AAaAAaAAAAAaAaaaaaaaaaaaaaAAAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]]
comp115911_c0_seq1	293	N	31	GGgGGgGGGGGgGgggggggggggggGGGGG	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]]
comp115911_c0_seq1	294	N	31	AAaAAaAAA.AaAaaaaaaaaaaaaaAAAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]]
comp115911_c0_seq1	295	N	32	A$AaAAaAAAAAaAaaaaaaaaaaaaaAAAAA^]A	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]>]]]]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	296	N	31	A$aAAaAAAAAaAaaaaaaaaaaaaaAAAAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]>]]]]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	297	N	30	tTTtTTTTTtTtttttttttttttTTTTTT	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	>]]]]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	298	N	30	gGGgGGGGGgGgggggggggggggGGGGGG	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	>]]]]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	299	N	30	aAAaAAAAAaAaaaaaaaaaaaaaAAAAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	>]]]]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	300	N	30	aAAaAAAAAaAaaaaaaaaaaaaaAAAAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	>]]]]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	301	N	30	a$AAaAAAAAaAaaaaaaaaaaaaaAAAAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	>]]]]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	302	N	29	CCcCCCCCcCcccccccccccccCCCCCC	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	303	N	29	T$T$tTTTTTtTtttttttttttttTTTTTT	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	304	N	27	g$GGGGGgGgggggggggggggGGGGGG	!!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	305	N	26	TTTTTtTtttttttttttttTTTTTT	!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	306	N	26	AAAAAaAaaaaaaaaaaaaaAAAAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	307	N	26	AAAAAaAaaaaaaaaaaaaaAAAAAA	!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	308	N	26	T$TTTTtTtttttttttttttTTTTTT	!!!!!!!!!!!!!!!!!!!!!!!!!!	]]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	309	N	25	G$G$GGgGgggggggggggggGGGGGG	!!!!!!!!!!!!!!!!!!!!!!!!!	]]>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	310	N	23	GGgGgggggggggggggGGGGGG	!!!!!!!!!!!!!!!!!!!!!!!	>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	311	N	23	AAaAaaaaaaaaaaaaaAAAAAA	!!!!!!!!!!!!!!!!!!!!!!!	>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	312	N	23	A$A$a$A$aaaaaaaaaaaaaAAAAAA	!!!!!!!!!!!!!!!!!!!!!!!	>]]]]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	313	N	19	aaaaaaaaaaaaaAAAAAA	!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	314	N	19	a$a$tttttttttttTTTTTT	!!!!!!!!!!!!!!!!!!!	]]]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	315	N	17	cccccccccccCCCCCC	!!!!!!!!!!!!!!!!!	]]]]]]>]]]]>]]]]]
comp115911_c0_seq1	316	N	18	cccccccccccCCCCCC^]c	!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]>]]]]]]
comp115911_c0_seq1	317	N	19	a$g$g$ggggggggGGGGGGg^]g	!!!!!!!!!!!!!!!!!!!	]]]]]]>]]]]>]]]]]]]
comp115911_c0_seq1	318	N	16	aaaaaaaaAAAAAAaa	!!!!!!!!!!!!!!!!	]]]>]]]]>]]]]]]]
comp115911_c0_seq1	319	N	16	a$aaaaaaaAAAAAAaa	!!!!!!!!!!!!!!!!	]]]>]]]]>]]]]]]]
comp115911_c0_seq1	320	N	15	a$a$c$c$c$c$cCCCCCCcc	!!!!!!!!!!!!!!!	]]>]]]]>]]]]]]]
comp115911_c0_seq1	321	N	9	a$TTTTTTtt	!!!!!!!!!	]>]]]]]]]
comp115911_c0_seq1	322	N	9	GGGGGGgg^>g	!!!!!!!!!	>]]]]]]]>
comp115911_c0_seq1	323	N	9	AAAAAAaaa	!!!!!!!!!	>]]]]]]]>
comp115911_c0_seq1	324	N	9	TTTTTTttt	!!!!!!!!!	>]]]]]]]>
comp115911_c0_seq1	325	N	9	GGGGGGggg	!!!!!!!!!	>]]]]]]]>
comp115911_c0_seq1	326	N	9	A$AA$AAAaaa	!!!!!!!!!	>]]]]]]]>
comp115911_c0_seq1	327	N	7	C$CCCccc	!!!!!!!	]]]]]]>
comp115911_c0_seq1	328	N	6	TTTttt	!!!!!!	]]]]]>
comp115911_c0_seq1	329	N	6	TTTttt	!!!!!!	]]]]]>
comp115911_c0_seq1	330	N	6	GGGggg	!!!!!!	]]]]]>
comp115911_c0_seq1	331	N	6	TTTttt	!!!!!!	]]]]]>
comp115911_c0_seq1	332	N	6	TTTttt	!!!!!!	]]]]]>
comp115911_c0_seq1	333	N	6	TTTttt	!!!!!!	]]]]]>
comp115911_c0_seq1	334	N	6	CCCccc	!!!!!!	]]]]]>
comp115911_c0_seq1	335	N	6	AAAaaa	!!!!!!	]]]]]>
comp115911_c0_seq1	336	N	6	T$TTttt	!!!!!!	]]]]]>
comp115911_c0_seq1	337	N	5	CCccc	!!!!!	]]]]>
comp115911_c0_seq1	338	N	5	AAaaa	!!!!!	]]]]>
comp115911_c0_seq1	339	N	5	AAaaa	!!!!!	]]]]>
comp115911_c0_seq1	340	N	5	TTttt	!!!!!	]]]]>
comp115911_c0_seq1	341	N	5	TTttt	!!!!!	]]]]>
comp115911_c0_seq1	342	N	5	T$Tttt	!!!!!	]]]]>
comp115911_c0_seq1	343	N	4	Cccc	!!!!	]]]>
comp115911_c0_seq1	344	N	4	Gggg	!!!!	]]]>
comp115911_c0_seq1	345	N	4	Aaaa	!!!!	]]]>
comp115911_c0_seq1	346	N	4	Cccc	!!!!	]]]>
comp115911_c0_seq1	347	N	4	T$ttt	!!!!	]]]>
comp115911_c0_seq1	348	N	3	ttt	!!!	]]>
comp115911_c0_seq1	349	N	3	ttt	!!!	]]>
comp115911_c0_seq1	350	N	3	aaa	!!!	]]>
comp115911_c0_seq1	351	N	3	aaa	!!!	]]>
comp115911_c0_seq1	352	N	3	aaa	!!!	]]>
comp115911_c0_seq1	353	N	3	ttt	!!!	]]>
comp115911_c0_seq1	354	N	3	ttt	!!!	]]>
comp115911_c0_seq1	355	N	3	ttt	!!!	]]>
comp115911_c0_seq1	356	N	3	ttt	!!!	]]>
comp115911_c0_seq1	357	N	3	aaa	!!!	]]>
comp115911_c0_seq1	358	N	3	aaa	!!!	]]>
comp115911_c0_seq1	359	N	3	ttt	!!!	]]>
comp115911_c0_seq1	360	N	3	ggg	!!!	]]>
comp115911_c0_seq1	361	N	3	aaa	!!!	]]>
comp115911_c0_seq1	362	N	3	aaa	!!!	]]>
comp115911_c0_seq1	363	N	3	ttt	!!!	]]>
comp115911_c0_seq1	364	N	3	ttt	!!!	]]>
comp115911_c0_seq1	365	N	3	aaa	!!!	]]>
comp115911_c0_seq1	366	N	3	ttt	!!!	]]>
comp115911_c0_seq1	367	N	3	aaa	!!!	]]>
comp115911_c0_seq1	368	N	3	t$tt	!!!	]]>
comp115911_c0_seq1	369	N	2	g$g	!!	]>
comp115911_c0_seq1	370	N	1	t	!	>
comp115911_c0_seq1	371	N	1	t	!	>
comp115911_c0_seq1	372	N	1	g$	!	>
comp115911_c0_seq1	374	N	1	^]a	!	]
comp115911_c0_seq1	375	N	1	c	!	]
comp115911_c0_seq1	376	N	1	t	!	]
comp115911_c0_seq1	377	N	1	a	!	]
comp115911_c0_seq1	378	N	1	a	!	]
comp115911_c0_seq1	379	N	1	a	!	]
comp115911_c0_seq1	380	N	1	t	!	]
comp115911_c0_seq1	381	N	1	t	!	]
comp115911_c0_seq1	382	N	1	a	!	]
comp115911_c0_seq1	383	N	1	a	!	]
comp115911_c0_seq1	384	N	1	t	!	]
comp115911_c0_seq1	385	N	1	t	!	]
comp115911_c0_seq1	386	N	1	a	!	]
comp115911_c0_seq1	387	N	1	a	!	]
comp115911_c0_seq1	388	N	1	t	!	]
comp115911_c0_seq1	389	N	2	a^]a	!!	]]
comp115911_c0_seq1	390	N	2	tt	!!	]]
comp115911_c0_seq1	391	N	2	tt	!!	]]
comp115911_c0_seq1	392	N	2	aa	!!	]]
comp115911_c0_seq1	393	N	2	aa	!!	]]
comp115911_c0_seq1	394	N	3	tt^]t	!!!	]]]
comp115911_c0_seq1	395	N	13	ggg^]g^]g^]g^]g^]g^]g^]g^]g^]g^]g	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	396	N	14	aaaaaaaaaaaaa^]a	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	397	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	398	N	14	gggggggggggggg	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	399	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	400	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	401	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	402	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	403	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	404	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	405	N	14	cccccccccccccc	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	406	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	407	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	408	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	409	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	410	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	411	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	412	N	14	gggggggggggggg	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	413	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	414	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	415	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	416	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	417	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	418	N	14	gggggggggggggg	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	419	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	420	N	14	gggggggggggggg	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	421	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	422	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	423	N	14	aaaaaaaaaaaaaa	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	424	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	425	N	14	tttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	426	N	14	aaaaaaaaaaaaaa+1t	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	427	N	14	a$ttttttttttttt	!!!!!!!!!!!!!!	]]]]]]]]]]]]]]
comp115911_c0_seq1	428	N	13	ggggggggggggc	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	429	N	13	aaaaaaaaaaaaa	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	430	N	13	ttttttttttttt	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	431	N	13	aaaaaaaaaaaaa	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	432	N	13	aaaaaaaaaaaaa	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	433	N	13	ttttttttttttt	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	434	N	13	aaaaaaaaaaaaa	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	435	N	13	aaaaaaaaaaaaa	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	436	N	13	aaaaaaaaaaaaa	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	437	N	13	aaaaaaaaaaaaa	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	438	N	13	ttttttttttttt	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	439	N	13	ggggggggggggg	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	440	N	13	aaaaaaaaaaaaa	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	441	N	13	aaaaaaaaaaaaa	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	442	N	13	a$tttttttttttt	!!!!!!!!!!!!!	]]]]]]]]]]]]]
comp115911_c0_seq1	443	N	12	tttttttttttt	!!!!!!!!!!!!	]]]]]]]]]]]]
comp115911_c0_seq1	444	N	12	cccccccccccc	!!!!!!!!!!!!	]]]]]]]]]]]]
comp115911_c0_seq1	445	N	12	gggggggggggg	!!!!!!!!!!!!	]]]]]]]]]]]]
comp115911_c0_seq1	446	N	12	t$ttttttttttt	!!!!!!!!!!!!	]]]]]]]]]]]]
comp115911_c0_seq1	447	N	11	gg$ggggg$gg$g$g	!!!!!!!!!!!	]]]]]]]]]]]
comp115911_c0_seq1	448	N	7	a$a$a$a$a$a$a$	!!!!!!!	]]]]]]]
